name: Publish

on: 
  release:
    types: [published]

jobs:
  publish-proxy:
    name: Publish proxy for ${{ matrix.goos }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish binaries to release
        uses: wangyoucao577/go-release-action@v1.17
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: "amd64"
          project_path: "./cmd/proxy"
          goversion: "1.16"
          binary_name: "aws-vault-proxy"
  publish-docker-exec:
    name: Publish docker-exec for linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish binaries to release
        uses: wangyoucao577/go-release-action@v1.17
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: "linux"
          goarch: "amd64"
          project_path: "./cmd/docker-exec"
          goversion: "1.16"
          binary_name: "aws-vault-proxy-docker-exec"